apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: coupon-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coupon-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 44
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi